/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoravoz;

import Voz.ReconocimientoVoz;
import javax.swing.JOptionPane;

public class Calculadora extends javax.swing.JFrame implements Runnable {

    private double operando1;
    private double operando2;
    private double resultado;
    
    /**Permite saber si se ejecuto una accion matematica*/
    private boolean presionadoAccion;
    
    /**Permite saber cuan es la accion(Operacion) matematica que se ejecuto*/
    private byte accion;
    public ReconocimientoVoz escuchar;
    public Thread hiloEscucha;

    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        this.presionadoAccion = false;
        this.txtNumero.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        txtNumero = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        btnX_2 = new javax.swing.JButton();
        btnInversa = new javax.swing.JButton();
        btnAbsoluto = new javax.swing.JButton();
        btnModulo = new javax.swing.JButton();
        btnBorrarTodo = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnX_Y = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btn10_2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnBorrarTodo1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();

        jButton9.setText("jButton9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 229, 255));

        txtNumero.setEditable(false);
        txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumero.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(6, 0));

        btnX_2.setText("x^2");
        jPanel1.add(btnX_2);

        btnInversa.setText("1/x");
        jPanel1.add(btnInversa);

        btnAbsoluto.setText("| x |");
        jPanel1.add(btnAbsoluto);

        btnModulo.setText("mod");
        jPanel1.add(btnModulo);

        btnBorrarTodo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBorrarTodo.setText("C");
        btnBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarTodo);

        btnRaiz.setText("sqrt()");
        jPanel1.add(btnRaiz);
        jPanel1.add(jButton7);
        jPanel1.add(jButton20);

        btnFactorial.setText("n!");
        jPanel1.add(btnFactorial);

        btnDivision.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivision);

        btnX_Y.setText("x^y");
        jPanel1.add(btnX_Y);

        btn7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn7.setText("7");
        jPanel1.add(btn7);

        btn8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn8.setText("8");
        jPanel1.add(btn8);

        btn9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn9.setText("9");
        jPanel1.add(btn9);

        btnMultiplicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMultiplicacion.setText("X");
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiplicacion);

        btn10_2.setText("10^2");
        btn10_2.setMaximumSize(new java.awt.Dimension(75, 50));
        btn10_2.setMinimumSize(new java.awt.Dimension(75, 50));
        btn10_2.setPreferredSize(new java.awt.Dimension(75, 50));
        jPanel1.add(btn10_2);

        btn4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn4.setText("4");
        jPanel1.add(btn4);

        btn5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn5.setText("5");
        jPanel1.add(btn5);

        btn6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn6.setText("6");
        jPanel1.add(btn6);

        btnResta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnResta);

        btnLog.setText("log");
        jPanel1.add(btnLog);

        btn1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn1.setText("1");
        jPanel1.add(btn1);

        btn2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn2.setText("2");
        jPanel1.add(btn2);

        btn3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn3.setText("3");
        jPanel1.add(btn3);

        btnSuma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuma);

        btnBorrarTodo1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnBorrarTodo1.setForeground(new java.awt.Color(255, 0, 0));
        btnBorrarTodo1.setText("Rec");
        btnBorrarTodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodo1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarTodo1);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        btn0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn0.setText("O");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        btnResultado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnResultado.setText("=");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        this.undirBoton((byte) 1);
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        this.undirIgual();
    }//GEN-LAST:event_btnResultadoActionPerformed

    public void undirIgual() {
        this.operando2 = Double.parseDouble(this.txtNumero.getText());
        this.mostrarResultado();
    }

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        this.undirBoton((byte) 2);
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        this.undirBoton((byte) 4);
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        this.undirBoton((byte) 3);
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodoActionPerformed
        this.borrarTodo();
    }//GEN-LAST:event_btnBorrarTodoActionPerformed

    private void btnBorrarTodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodo1ActionPerformed
        this.iniciarReconocimieto();
        JOptionPane.showMessageDialog(rootPane, "Reconocimiento de voz iniciado"
                + "\ncorrectamente....!!", "Comando", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnBorrarTodo1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn0ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    public void borrarTodo() {
        this.txtNumero.setText("");
    }

    private void iniciarReconocimieto() {
        hiloEscucha = new Thread(escuchar = new ReconocimientoVoz(this));
        hiloEscucha.start();
    }

    public void undirBoton(byte accion) {
        this.operando1 = Double.parseDouble(this.txtNumero.getText());
        this.txtNumero.setText("");
        this.accion = accion;
    }

    public void mostrarResultado() {
        switch (this.accion) {
            case 1:
                this.resultado = this.operando1 + this.operando2;
                break;
            case 2:
                this.resultado = this.operando1 - this.operando2;
                break;
            case 3:
                this.resultado = this.operando1 * this.operando2;
                break;
            case 4:
                this.resultado = this.operando1 / this.operando2;
                break;
        }
        this.presionadoAccion = false;
        this.txtNumero.setText(Double.toString(this.resultado));
    }

    /**
     * Escribe en la pantalla un numero(0 a 9), que es representado como un
     * caracter de tipo string
     *
     * @param numero string que representa un numero del 0 a 9, se debe tener
     * cuidado este parametro es un string y no se puede operar solo se mostrara
     * en la pantalla de la calculadora
     */
    public void escribirEnPantalla(String numero) {
        this.txtNumero.setText(this.txtNumero.getText() + numero);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10_2;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAbsoluto;
    private javax.swing.JButton btnBorrarTodo;
    private javax.swing.JButton btnBorrarTodo1;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnInversa;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnModulo;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnX_2;
    private javax.swing.JButton btnX_Y;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txtNumero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
